const menu=document.querySelector(".menu"),nav=document.querySelector("nav");menu.onclick=()=>nav.classList.toggle("open");
const theme=document.getElementById("themeBtn"); if(localStorage.getItem("labib-theme")==="light")document.body.classList.add("light");
theme.onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("labib-theme",document.body.classList.contains("light")?"light":"dark")};
document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>nav.classList.remove("open"));
document.getElementById("year").textContent=new Date().getFullYear();
const modal=document.getElementById("modal"),content=document.getElementById("modalContent");
const data={
password:{title:"Password Security Tool",text:"Version 1.0 desktop application built with Python and Tkinter. It evaluates password strength, calculates entropy, estimates crack time, checks breached passwords using the Have I Been Pwned API, generates passwords and passphrases, maintains history and session statistics, supports dark/light mode, and exports PDF security reports.",tech:"Python • Tkinter • Have I Been Pwned API",imgs:["assets/password-home-dark.png","assets/password-generator.png","assets/password-history.png","assets/password-breach-detection.png","assets/password-statistics.png","assets/password-pdf-report.png"], captions:["Password analysis — dark mode","Password generator","Password history","Breach detection","Session statistics","Exported security report"]},
pharma:{title:"PharmaLIMS",text:"A web-based Laboratory Information Management System designed around pharmaceutical laboratory workflows. The project covers authentication, sample management, test assignment, results, OOS investigation and structured laboratory records.",tech:"PHP • MySQL • HTML • CSS • JavaScript • XAMPP",imgs:["assets/pharmalims.png"], captions:["PharmaLIMS project interface"]},
gluco:{title:"GlucoBondhu",text:"An AI-assisted diabetes monitoring platform designed to support community pharmacists and patients through structured health tracking, dashboards, reminders, history and pharmacist–patient interaction. The following screens show the main user flow and healthcare tracking features.",tech:"Flutter • Mobile • AI • Healthcare IT",imgs:["assets/gluco-role-selection.png","assets/gluco-patient-login.png","assets/gluco-glucose-tracking.png","assets/gluco-health-insights.png","assets/gluco-glucoai.png","assets/gluco-profile-health.png","assets/gluco-medication-reminder.png","assets/gluco-activity.png","assets/gluco-meal-tracking.png","assets/gluco-notifications.png"],captions:["Role selection","Patient login and ID selection","Glucose tracking and 7-day trend","Health insights","GlucoAI assistant","Profile and health information","Medication reminders","Activity tracking","Meal tracking","Notifications"]}
};
document.querySelectorAll("[data-modal]").forEach(b=>b.onclick=()=>{let p=data[b.dataset.modal];content.innerHTML=`<p class="cmd">$ cat project.md</p><h2>${p.title}</h2><p>${p.text}</p><p><strong>Technologies:</strong> ${p.tech}</p><div class="modal-gallery">${p.imgs.map((x,i)=>`<figure><img src="${x}" alt="${p.title} screenshot ${i+1}"><figcaption>${p.captions?.[i]||"Project screenshot"}</figcaption></figure>`).join("")}</div>`;modal.classList.add("open")});
document.querySelector(".close").onclick=()=>modal.classList.remove("open");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("open")};document.onkeydown=e=>{if(e.key==="Escape")modal.classList.remove("open")};
